### ISSUE TITLE
Any one can help me to build a full .ipa file?

### ISSUE THREAD

**Issue by Cyril1992** [levinli303/MobileCelestia#9]
Any one can help me to build a full .ipa file? I have no ios development enviroment, thanks a lot

**Comment by Cyril1992** [comment]
> Hi. What do you need an IPA for? It is currently not possible to side load Celestia. Please use https://testflight.apple.com/join/VPp0g68O to join beta.



Thanks for your reply.

I'm a teaching assistant at a Malaysian high school. I'd like to replacing the scripting, or install some new add-on for teaching purpose.

For instance, modify the demo.cel which under \Payload\Celestia.app\CelestiaResources\ directly via unpack and repack .ipa, and then distribute the modified app via testflight.

I know the alternative way is import the file to CelestiaResources/Scripts via document, but it's hard to control many young and unskilled students to do the such complex way in the class. 

Thus, I can distribute the revised app via testflight as the app is not for public, and no need care the expire date (90 days I remember) due to short term use. It could be much easier for student download the app via a testflight link like you gave me today.

I am not an IOS developer, so my train of thought may wrong, pardon me if this feels like impossible in terms of technology. 

Could you send the .ipa to me via s2020293@siswa.um.edu.my? Please be assured I will keep all copyright of this software, just replacing scripts and add-on. Thanks.

**Comment by levinli303** [comment]
Hi thanks for the interest in using for teaching purpose, we'd like to help, however the approach you mentioned would not work.

We have IPAs publicly available but they are signed with AppStore certificate. You cannot just simply unpack an IPA and repack it and have it installed since iOS will prevent you from installing a modified IPA.

There are two approaches you can take:
1. Build the project on your own replacing some files in Celestia repo. Guide for building: https://github.com/levinli303/Celestia/wiki/Development and then distribute with enterprise/ad-hoc signing.
2. Use external folder to fully customize Celestia, it allows you to provide a folder for Celestia to read from other than the one provided in the app bundle. See https://github.com/levinli303/Celestia/wiki/Override-Data-Directory-to-Read-from

**Comment by Cyril1992** [comment]
> Hi thanks for the interest in using for teaching purpose, we'd like to help, however the approach you mentioned would not work.
> 
> We have IPAs publicly available but they are signed with AppStore certificate. You cannot just simply unpack an IPA and repack it and have it installed since iOS will prevent you from installing a modified IPA.
> 
> There are two approaches you can take:
> 
> 1. Build the project on your own replacing some files in Celestia repo. Guide for building: https://github.com/levinli303/Celestia/wiki/Development and then distribute with enterprise/ad-hoc signing. To distribute via TestFlight, it need to go through App Store review.
> 2. Use external folder to fully customize Celestia, it allows you to provide a folder for Celestia to read from other than the one provided in the app bundle. See https://github.com/levinli303/Celestia/wiki/Override-Data-Directory-to-Read-from

thanks a lot, bro. You are so kind. I will follow your instructions.
